openapi: 3.0.1
info:
  title: Nota Fiscal de Produto
  description: "# Introducão\nSeja bem-vindo a documentação da API de Nota Fiscal de Produto!\nNossa API foi criada utilizando o padrão REST que possibilita a integração de seu sistema ao nosso, sendo assim você também pode extender ou recriar as funcionalidades existentes na nossa plataforma, tudo isso consumindo a API que está documentada abaixo.\n\n\n# Como usar a API?\nLogo a seguir você encontrará todos os recursos e metódos suportados pela API, sendo que essa página possibilita que você te[...]"
  version: v2
servers:
  - url: https://api.nfse.io/
tags:
  - name: Companies
    description: |
      Utilize esta requisição para criar novas empresas plataforma para processar Documentos Fiscais. **Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.
  - name: Companies Certificates
    description: |
      Utilize esta requisição para fazer upload de um **Certificado da ICP-Brasil** do tipo **e-CNPJ A1** ou **NFE A1** em uma **Empresa** e vincula-lo para processamentos.

      O **Certificado da ICP-Brasil** funciona como uma identidade virtual, para empresas e pessoas, que permite a identificação segura e inequívoca do autor de uma mensagem ou transação feita em meios eletrônicos, como a web.
  - name: Companies State Taxes
    description: |
      Está sessão é destinada às **Incrições Estaduais(IE).** Uma **Incrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ.

      Utilizando as informações abaixo você pode criar novas IEs na empresa para processar **Documentos Fiscais.** Além disso, também é possível listar as IEs por empresa e consultar, alterar e exluir uma IE pelo ID da mesma.
  - name: Product Invoices
    description: "Nesta sessão estão disponíveis informações necessárias para emitir uma Nota Fiscal Eletrônica usando a nossa API. \n\nVocê também encontrará informações sobre consulta de uma nota fiscal por ID, consulta de uma lista de notas por empresa, consulta do PDF do Documento Auxiliar da Nota Fiscal Eletrônica (DANFE) e consulta do XML da nota fiscal eletrônica.\n"
  - name: WebHooks
    description: |
      Eventos ocorrem a todo instante na plataforma durante os processamentos e são registrados criando notificações para os webhooks ativos e configurados para receber os eventos.

      Um **Webhook** é semelhante a uma assinatura em um sistema de publicação e assinatura que permite ao assinante indicar quando, como e onde as notificações de eventos devem ser despachadas. Um **Webhook** é registrado e gerenciado por Conta o que significa que cada Conta tem um conjunto separado de ganchos que podem ser acionados por eventos gerados através de ações executadas por esse Conta. Ou seja, a **Conta da Empresa A** não verá os WebHooks disparados por uma ação executada pelo usuár[...]

      São identificados seguindo o padrão **Resource.EventAction**, sendo **Resource** o nome da entidade que gerou o evento e **EventAction** o nome do evento e ação criados.

      Esses tipos podem ser utilizados como filtro ao criar ou alterar um webhook, sendo que o filtro determina quais notificações de eventos e ação serão enviadas para um determinado webhook, ou seja, dependendo de quais filtros são vinculados ao webhook ele só receberá as notificações de evento e ação que correspondem a um ou mais desses filtros
paths:
  /v2/companies:
    get:
      tags:
        - Companies
      summary: Consultar todas as Empresas da Conta
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar os dados das empresas vinculadas a conta."
      operationId: V2CompaniesGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    post:
      tags:
        - Companies
      summary: Criar uma Empresa
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para criar novas empresas plataforma para processar Documentos Fiscais.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais."
      operationId: V2CompaniesPost
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{company_id}:
    get:
      tags:
        - Companies
      summary: Consultar uma Empresa pelo ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar os dados de uma empresas pelo ID."
      operationId: V2CompaniesByCompany_idGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    put:
      tags:
        - Companies
      summary: Alterar uma Empresa pelo ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para alterar os dados de uma empresas pelo ID."
      operationId: V2CompaniesByCompany_idPut
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    delete:
      tags:
        - Companies
      summary: Excluir uma Empresa por ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para excluir uma empresas pelo ID, cuidado pois esse processo é irreversível."
      operationId: V2CompaniesByCompany_idDelete
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{company_id}/certificates:
    get:
      tags:
        - Companies Certificates
      summary: Consultar um Certificado por seu Status
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar os dados de um **Certificado da ICP-Brasil** através d0 **status do certificado** (__status__)."
      operationId: V2CompaniesByCompany_idCertificatesGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    post:
      tags:
        - Companies Certificates
      summary: Upload de um Certificado
      description: "### Informações adicionais\r\n\r\nUtilize esta requisição para fazer upload de um **Certificado da ICP-Brasil** do tipo __e-CNPJ A1__ ou __NFE A1__ em uma **Empresa** e vincula-lo para processamentos.\r\n\r\nO **Certificado da ICP-Brasil** funciona como uma identidade virtual, para empresas e pessoas, que permite a identificação segura e inequívoca do autor de uma mensagem ou transação feita em meios eletrônicos, como a web."
      operationId: V2CompaniesByCompany_idCertificatesPost
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{company_id}/certificates/{certificate_thumbprint}:
    get:
      tags:
        - Companies Certificates
      summary: Consultar um Certificado por sua impressão digital
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar os dados de um **Certificado da ICP-Brasil** através da **impressão digital do certificado** (__thumbprint__)."
      operationId: V2CompaniesByCompany_idCertificatesByCertificate_thumbprintGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    delete:
      tags:
        - Companies Certificates
      summary: Excluir um Certificado por sua impressão digital
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para excluir o **Certificado da ICP-Brasil** através da **impressão digital do certificado** (__thumbprint__) e desvincula-lo da **Empresa**.\r\n\r\n**ATENÇÃO pois esta requisição é irreversível**"
      operationId: V2CompaniesByCompany_idCertificatesByCertificate_thumbprintDelete
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{company_id}/statetaxes:
    get:
      tags:
        - Companies State Taxes
      summary: Listar as Inscrições Estaduais
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para listar as inscrições estaduais na empresa para processar __Documentos Fiscais__.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.\r\n**Inscrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ."
      operationId: V2CompaniesByCompany_idStatetaxesGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    post:
      tags:
        - Companies State Taxes
      summary: Criar uma Inscrição Estadual
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para criar novas inscrição estadual na empresa para processar __Documentos Fiscais__.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.\r\n**Inscrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ."
      operationId: V2CompaniesByCompany_idStatetaxesPost
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{company_id}/statetaxes/{state_tax_id}:
    get:
      tags:
        - Companies State Taxes
      summary: Consultar uma Inscrição Estadual pelo ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar os dados de uma empresas pelo ID.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.\r\n**Inscrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ."
      operationId: V2CompaniesByCompany_idStatetaxesByState_tax_idGet
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    put:
      tags:
        - Companies State Taxes
      summary: Alterar uma Inscrição Estadual pelo ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para alterar os dados de uma Inscrição Estadual pelo ID.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.\r\n**Inscrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ."
      operationId: V2CompaniesByCompany_idStatetaxesByState_tax_idPut
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
    delete:
      tags:
        - Companies State Taxes
      summary: Excluir uma Inscrição Estadual pelo ID
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para excluir uma Inscrição Estadual pelo ID, cuidado pois esse processo é irreversível.\r\n**Empresa** representa uma pessoa jurídica que precisa processar Documentos Fiscais.\r\n**Inscrição Estadual** representa os dados necessários sobre o cadastro Estadual (ICMS) que é preciso para processar Documentos Fiscais na SEFAZ."
      operationId: V2CompaniesByCompany_idStatetaxesByState_tax_idDelete
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/companies/{companyId}/productinvoices:
    get:
      tags:
        - Product Invoices
      summary: Listar as Notas Fiscais Eletrônicas (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar uma lista de notas fiscais eletrônicas por empresa."
    post:
      tags:
        - Product Invoices
      summary: Emitir uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para enviar uma Nota Fiscal Eletrônica (NFE) para fila de emissão.\r\n**ATENÇÃO**: O processamento será feito de forma assíncrona, ou seja, o retorno positivo\r\nnão garante a emissão do documento fiscal.\r\nPara obter um retorno ao final do processo de emissão de uma Nota Fiscal Eletrônica (NFe), recomendamos\r\nutilizar os WebHooks."
  /v2/companies/{companyId}/productinvoices/{invoiceId}:
    get:
      tags:
        - Product Invoices
      summary: Consultar por ID uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar os dados de uma Nota Fiscal Eletrônica (NFE) pelo ID."
    delete:
      tags:
        - Product Invoices
      summary: Cancelar uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para enviar uma Nota Fiscal Eletrônica (NFE) para fila de cancelamento.\r\n**ATENÇÃO**: O processamento será feito de forma assíncrona, ou seja, o retorno positivo\r\nnão garante o cancelamento do documento fiscal.\r\nPara obter um retorno ao final do processo de cancelamento de uma Nota Fiscal Eletrônica (NFe),\r\nrecomendamos utilizar os WebHooks."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/items:
    get:
      tags:
        - Product Invoices
      summary: Consultar os produtos por ID uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar os dados de uma Nota Fiscal Eletrônica (NFE) pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/events:
    get:
      tags:
        - Product Invoices
      summary: Consultar eventos por ID uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar os dados de uma Nota Fiscal Eletrônica (NFE) pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/pdf:
    get:
      tags:
        - Product Invoices
      summary: Consultar PDF do Documento Auxiliar da Nota Fiscal Eletrônica (DANFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar a URL para o Documento Auxiliar Nota Fiscal Eletrônica (DANFE)\r\nem formato de arquivo PDF."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/xml:
    get:
      tags:
        - Product Invoices
      summary: Consultar XML da Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar os dados de uma nota fiscal Eletrônica pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/xml/rejection:
    get:
      tags:
        - Product Invoices
      summary: Consultar XML de rejeição da Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar o motivo da rejeição de uma nota fiscal Eletrônica pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/xml-rejection:
    get:
      tags:
        - Product Invoices
      summary: Consultar XML de rejeição da Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar o motivo da rejeição de uma nota fiscal Eletrônica pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/xml-epec:
    get:
      tags:
        - Product Invoices
      summary: Consultar XML da autorização em contingência (EPEC)
  /v2/companies/{companyId}/productinvoices/{invoiceId}/correctionletter:
    put:
      tags:
        - Product Invoices
      summary: Enviar uma carta de correção para Nota Fiscal Eletrônica (CC-e)
      description: "### Informações adicionais\r\nUtilize esta requisição para enviar uma carta de correção na Nota Fiscal Eletrônica (NFE).\r\n**ATENÇÃO**: O processamento será feito de forma assíncrona, ou seja, o retorno positivo\r\nnão garante a execução do documento fiscal.\r\nPara obter um retorno ao final do processo de carta de correção de uma Nota Fiscal Eletrônica (NFe),\r\nrecomendamos utilizar os WebHooks."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/correctionletter/pdf:
    get:
      tags:
        - Product Invoices
      summary: Consultar PDF do Documento Auxiliar da Nota Fiscal Eletrônica (DANFE) de Carta de Correção (CC-e)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar a URL para o Documento Auxiliar Nota Fiscal Eletrônica (DANFE)\r\nem formato de arquivo PDF."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/correctionletter/xml:
    get:
      tags:
        - Product Invoices
      summary: Consultar XML da Carta de Correção Eletrônica (CC-e)
      description: "### Informações adicionais\r\nUtilize esta requisição para consultar os dados da carta de correção de uma nota fiscal Eletrônica pelo ID."
  /v2/companies/{companyId}/productinvoices/{invoiceId}/disablement:
    post:
      tags:
        - Product Invoices
      summary: Inutilizar uma Nota Fiscal Eletrônica (NFE)
      description: "### Informações adicionais\r\nUtilize esta requisição para enviar uma Nota Fiscal Eletrônica (NFE) para fila de inutilização.\r\n**ATENÇÃO**: O processamento será feito de forma assíncrona, ou seja, o retorno positivo\r\nnão garante a inutilização do documento fiscal.\r\nPara obter um retorno ao final do processo de inutilização de uma Nota Fiscal Eletrônica (NFe),\r\nrecomendamos utilizar os WebHooks."
  /v2/companies/{companyId}/productinvoices/disablement:
    post:
      tags:
        - Product Invoices
      summary: Inutilizar números de nota fiscal
      description: "### Informações adicionais\r\nCaso seja um único número, utilizar o Número inicial e o Número final com o mesmo valor"
  /v2/companies/{companyId}/statetaxes/{statetaxId}/productinvoices:
    post:
      tags:
        - Product Invoices
      summary: Emitir uma Nota Fiscal Eletrônica (NFE) Informando um StateTaxId
      description: "### Informações adicionais\r\nUtilize esta requisição para enviar uma Nota Fiscal Eletrônica (NFE) para fila de emissão.\r\n**ATENÇÃO**: Cada processamento será feito de forma assíncrona, ou seja, o retorno positivo\r\nnão garante a emissão do documento fiscal.\r\nPara obter um retorno ao final do processo de emissão de uma Nota Fiscal Eletrônica (NFe), recomendamos\r\nutilizar os WebHooks."
  /v2/webhooks/eventtypes:
    get:
      tags:
        - WebHooks
      summary: Listar os Tipos de Eventos gerados pela plataforma
      description: "### Informações adicionais\r\n\r\nEventos ocorrem a todo instante na plataforma durante os processamentos e são registrados\r\ncriando notificações para os webhooks ativos e configurados para receber os eventos.\r\n            \r\nSão identificados seguindo o padrão **Resource.EventAction**,\r\nonde **Resource**: nome da entidade que gerou o evento;\r\n**EventAction**: nome do evento e ação criados.\r\n\r\nEsse tipos podem ser utilizados como filtro ao criar ou alterar um web[...]"
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
  /v2/webhooks:
    get:
      tags:
        - WebHooks
      summary: Listar os Webhooks
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar uma lista de **Webhooks** cadastrados na Conta Autenticada."
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
    post:
      tags:
        - WebHooks
      summary: Criar um Webhook
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para criar novos **Webhooks** para receber as notificações de eventos ocorridos na plataforma.\r\n            \r\nNa criação do **Webhook** a URL informada no cadastro deve ser responsiva, ou seja, deverá responder *(HTTP Status 200 OK)* a uma requisição *(HTTP POST)* que será feita para testar se a URL está operando como normalmente, caso contrario uma mensagem de erro será retornada.\r\n            \r\nUm **Webhook*[...]"
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
    delete:
      tags:
        - WebHooks
      summary: Excluir Todos os Webhooks existentes
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para excluir todos os **Webhooks** cadastrados para a Conta Autenticada."
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
  /v2/webhooks/{webhook_id}:
    get:
      tags:
        - WebHooks
      summary: Consultar um webhook existente
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para consultar um **Webhook** que esteja cadastrado e tenha o ID igual ao parametro **webhook_id**."
      operationId: RegistrationLookupAction
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
    put:
      tags:
        - WebHooks
      summary: Alterar um Webhook existente
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para alterar os dados do **Webhook** que esteja cadastrado e tenha o ID igual ao parametro **webhook_id** especificado."
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
    delete:
      tags:
        - WebHooks
      summary: Excluir um Webhook existente
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para excluir o **Webhook** que esteja cadastrado e tenha o ID igual ao parametro **webhook_id** especificado.\r\nA exclusão do **Webhook** não exime o **Webhook** excluído de receber os notificações de eventos, já ocorridos na plataforma, que ainda estejam em processo de retentativa de envio dos gatilhos."
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
  /v2/webhooks/{webhook_id}/pings:
    put:
      tags:
        - WebHooks
      summary: Criar notificação para Testar um webhook
      description: "### Informações adicionais\r\n \r\nUtilize esta requisição para criar uma notificação de teste (ping) em um **Webhook** já cadastrado.\r\n\r\nEsta ação irá criar um evento de notificação do tipo ping para o **Webhook** especificado, deste modo você poderá simular o recebimento de uma notificação de teste no **Webhook** cadastrado."
      security:
        - Authorization_Header:
            - readAccess
            - writeAccess
          Authorization_QueryParam:
            - readAccess
            - writeAccess
components:
  securitySchemes:
    Authorization_Header:
      type: apiKey
      description: Autenticar usando o cabeçalho HTTP
      name: Authorization
      in: header
    Authorization_QueryParam:
      type: apiKey
      description: Autenticar usando o parâmetro na URL
      name: apikey
      in: query
    Authorization_JwtBearer:
      type: http
      description: Autenticar usando o cabeçalho HTTP
      scheme: bearer
      bearerFormat: Json Web Token
security:
  - Authorization_Header: []
    Authorization_QueryParam: []
  - Authorization_JwtBearer: []
x-original-swagger-version: "2.0"
